export const HZ = 60;
export const STEP = 1 / HZ;
export const TILE = 40;
export const SPEED = 160;
export const RADIUS = 12;
export type Vec = { x: number; y: number };
export type Rect = Vec & { w: number; h: number };
export type Input = { x: number; y: number; aim: number; shoot: boolean; interact: boolean };
export const idle = (): Input => ({ x: 0, y: 0, aim: 0, shoot: false, interact: false });
export type Action = {
  tick: number;
  kind: 'shoot' | 'switch' | 'pickup' | 'drop' | 'death' | 'teleport';
  target?: string;
  aim?: number;
};
export type Run = {
  number: number;
  duration: number;
  inputs: Input[];
  checkpoints: (Vec & { tick: number })[];
  events: Action[];
  end: 'commit' | 'timeout' | 'complete';
};
export type Plate = Vec & { id: string; need?: number };
export type Switch = Vec & { id: string; seconds?: number; target?: boolean };
export type Door = Rect & { id: string; signals: string[]; echoOnly?: boolean };
export type Laser = Rect & {
  id: string;
  signals: string[];
  period?: number;
  on?: number;
  phase?: number;
};
export type Carryable = Vec & { id: string; kind: 'crate' | 'core'; holder?: number };
export type Turret = Vec & { id: string; range: number; shield?: string };
export type Portal = Vec & { id: string; to: Vec };
export type Level = {
  id: string;
  name: string;
  subtitle: string;
  objective: string;
  hint: string;
  seconds: number;
  par: number;
  spawn: Vec;
  exit: Vec;
  walls: Rect[];
  plates: Plate[];
  doors: Door[];
  switches: Switch[];
  lasers: Laser[];
  objects: Carryable[];
  turrets: Turret[];
  portals: Portal[];
  exitSignals?: string[];
  core?: boolean;
};
export type Actor = Vec & {
  id: number;
  aim: number;
  alive: boolean;
  cooldown: number;
  portalCooldown: number;
  desync: boolean;
  conflict: string;
  eventCursor: number;
  checkpointCursor: number;
  run?: Run;
};
export type Bullet = Vec & { vx: number; vy: number; hostile: boolean; life: number };
export type Feedback = Vec & {
  kind: 'shot' | 'impact' | 'signal' | 'death' | 'teleport' | 'warning';
  text?: string;
};
